<?php include('server.php');

 ?>

<!DOCTYPE html>
<html>
<head>
	<title>Terms and Condition</title>
	<meta charset="utf-8">
  	



</head>

<body>
<!--Navbar menu-->
<?php include('header.php')?>
<!--End Navbar menu-->

<h1 style = "margin-left: 100px; margin-top: 3%; margin-bottom: 2%; font-size: 50px;"> <b>Learn From USASS Service Terms & Conditions </b> </h1>
 
<h2 style = "margin-left: 230px;"><b> General Terms</b> </h2>

<h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> By accessing and registering in our website, you confirm that you are in agreement with and bound by the terms and conditons
    outlined below. These terms apply to the entire website and any email or other type of communication between you and other users.<br><br></h5>

<h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> Under no circumstances shall team be liable for any direct, indirect, special, incidental or consequential damages, including, 
    but not limited to, loss of data or profit , arising out of the use, or the inability to use, the materials on this site, even the team or an authorized representative has been advised
    of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair, or correction of equipment or data, you assume any cost thereof.<br><br></h4>

<h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> Will not be responsible for any outcome that may occur during the course or usage of our resources. We reserve this rights to change prices and revise the resources usage policy in any moment.<br><br></h4> 



  <h2 style = "margin-left: 230px;"><b> Definition and Key Terms</b> <h2>
<h4 style = "margin-left: 230px;"> For this Terms and Conditions <br><br></h4>

    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>Cookies:</b> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you
    such as your language preference or login information. <br><br></h4>
  
    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>Company:</b> when this policy mentions it refers to USASS, Gen. Luna St., Iloilo City, PH that is responsible for your information under this privacy policy. <br><br></h4> 
    
  
    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>Country:</b> where USASS or the owners/developer of USASS are based, in this case is PHILIPPINES.<br><br></h4> 
    
    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>Customer:</b> refers to the company, organization or person that signs up to use the USASS service to manage the relationships with your consumers or service users.<br><br></h4>
    
    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>Device:</b> any internet connected device such as laptop, computer, tablet can be used to visit USASS and use the services. <br><br></h4>
    
    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>IP address:</b> every device connected to the internet is assigned a number known as an internet protocol (IP) address. These numbers are usually assigned in geographic blocks.
            An IP address can be often be used to identify the location from which a device is connecting to the internet.<br><br></h4>
    
    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>Personnel:</b> refers to those who are employed by USASS or are under contract to manage the website in behalf of one of the parties.<br><br></h4>

    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>Personal Data:</b> any information that directly, indirectly, or in connection with other information -- including a university email -- allows or the identification or identifiability of a natural person. <br><br></h4>

    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>Service:</b> refers to the service provided by the freelancers in USASS website as described in relative terms in this platform.<br><br></h4>

     <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> <b>You:</b> a person or identity that is registered with USASS to use the platform. <br><br></h4>
            





<h2 style = "margin-left: 230px;"> <b>License </b></h2>

<h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> USASS grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use our service strictly in accordance with the terms of this agreement.<br><br></h4>

<h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> These Terms and Conditions are a contract between you and USASS, the provider of the USASS website and the services accessible from the USASS website. <br><br></h4>

<h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> You are agreeing to be bound by these terms and conditions. If you don't agree to these terms and conditions, please do not use the service. In these terms and conditions,
  "you" refers both to you as an individual and to the entity you represent. If you violate any of these terms and conditions, we reserve the right to cancel your account or block access to your account without notice.  <br><br></h4>   


 <h2 style = "margin-left: 230px;"> <b>Restrictions</b></h2>           
    <h4 style = "margin-left: 230px;">You agree not to, and you will not permit others to: <br><br></h4>
    
    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> License, sell, rent, lease, assign or otherwise commercially exploit the service or make the platform available to any third party.<br><br></h4>
    
    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the service.<br><br></h4>

    <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;">  Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of or its affiliates, partners, suppliers or the licensors of the service.<br><br></h4>

     
      
  <h2 style = "margin-left: 230px;"> <b>Your Suggestions</b></h2>  

      <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;">Any feedback, comments, ideas, improvements or suggestions provided by you to us with respect to the service shall remain the sole and exclusively property of us.
          We shall be free to use, copy, modify, publish, or redistribute the suggestions for any purposes and in any way without any credit or compensation with you.<br><br></h4> 
  
 <div id="mydiv3">
  <h2 style = "margin-left: 230px;"> <b>Your Consent</b></h2>  
  
   <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> We've updated our terms and conditions to provide you with complete transparency into what is being set when you visit our site
       and how it's be used. By using this website, registering account, listing a service, and post a request, you hereby consent to our terms and conditions.<br><br></h4>

<h2 style = "margin-left: 230px;"><b> Cookies</b></h2>  

     <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> We use "Cookies" to identify the areas of our website that you have visited. A cookie is a small piece of data stored on your computer. 
         We use Cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these Cookies, certain functionality like videos, may become unavailable or you would be
         required to enter your login details every time you visit our platform as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to 
         access functionality on our website correctly at all. We never place Personally Identifiable information in Cookies. <br><br></h4>

<h2 style = "margin-left: 230px;"> <b>Change To Our Terms and Conditions</b></h2>  

          <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> You acknowledge and agree that we may stop (permanently or temporarily) providing the service (or any features within the service) to you without prior noticed. You
              may stop at any time. You don't need to specifically inform us when you stop using the platform. You acknowledge and agree that if we disable access to your account, you may be prevented from accessing the website, your details or any files or other materials
              which is obtained in your account. If we decided to change our Terms and Conditions, we will post those changes in this page, and/ update the Terms and Conditions modification date below.<br><br></h4>
         
    <h2 style = "margin-left: 230px;"><b> Term and Termination</b></h2>       
            <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> This agreement shall remain in effect until terminated by you or us. We may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice. This 
                agreement will terminate immediately, without prior notice from us, in the event that you may fail to comply with any provision of this agreement. You may also terminate this Agreement by deleting the service and all copies thereof from your computer.Upon termination of this agreement,
                you shall cease all use of the service and delete all copies of the service from your computer. Termination of this Agreement will not limit any of our rights or remedies at law or in equity in case breach by you(during the term of this Agreement) of any of your obligations under the present 
                Agreement.<br><br></h4>
 
    
     <div id="mydiv2">
     <h2 style = "margin-left: 230px;"> <b>Waiver</b></h2>
     <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;">  Except as provided herein, the failure to exercise the right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise
         such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach. <br><br></h4>
         
     
     
      <h2 style = "margin-left: 230px;"><b> Data Policy</b></h2> 
     
     <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas or new improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically 
         be treated as non-confidential and non-proprietary and will become the sole property of us without any compensation or credit to you whatsoever. We and our affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any 
         purposes in any medium in perpetuit, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas. <br><br></h4>
     
 
       <h2 style = "margin-left: 230px;"><b> Disclaimer</b></h2>
     
      <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"> Our website and its contents are provided "as is" and "as available" without any warranty or representations of any kind, wether express or implied. We are a distributor and not a publisher of the content supplied by the third parties; as such, our exercise
          no editorial control over such content and makes no warranty or representation as to the accuracy, reliability of any information, content, service or merchandise provided through our platform. Without limiting the foregoing, We specifically disclaim all warranties and representations in any content transmitted on or in connection with, our Service, including
          without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information
          given by us or any of its affiliates or the like will create a warranty. We do not warrant that our service will be uninterrupted, uncorrupted, timely, or error-free. <br><br></h4>
      
       
       
   
       <div> <h2 style = "margin-left: 230px;"><b> Contact Us </b></h2></div>
     
       <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"><ul> Via Email:<a href = "mailto: Usassad2023@gmail.com">Usassad2023@gmail.com </a></h4></ul>
       <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"><ul>  Via Phone Number:<a href="tel:09208076866"> 09208076866 </a></h4> </ul>
        <h4 style = "margin-left: 260px; margin-right: 260px; text-align: justify;"><ul> Via this Address: Ge. Luna St., Iloilo City Ph  </h4></ul> <br> <br> <br> <br> <br>
      
<!--Footer-->
<?php include 'footer.php'?>
<!--End Footer-->


<script type="text/javascript" src="jquery/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="dist/js/bootstrapValidator.js"></script>




<script>
$(".register").click(function(){
  $("#register").slideDown("slow");
  $("#login").slideUp("slow");
  $("#loginsvg").slideUp("slow");
  $("#registersvg").slideDown("slow");
});
$(".login").click(function(){
  $("#register").slideUp("slow");
  $("#login").slideDown("slow");
  $("#loginsvg").slideDown("fast");
  $("#registersvg").slideUp("slow");
});
</script>

</body>
</html>